### ISSUE TITLE
b.getTimezoneOffset is not a function

### ISSUE THREAD

**Issue by FNakano** [AtomGraph/LinkedDataHub#139] opened 2022-10-29 18:51 UTC
I believe you can help me with this... It is more of a Date/Time encoding issue - not a LinkedDataHub issue.

http://50.62.81.50:8890/sparql is a SPARQL endpoint. The database has some data in it. 

In LinkedDataHub I created a service, to access it and run the query: 

```
prefix sosa: <http://www.w3.org/ns/sosa/>

select * where {
  ?s ?p sosa:Observation .
  ?s sosa:hasSimpleResult ?o1 .
  ?s sosa:resultTime ?o2 .
} LIMIT 100
```
... got a `b.getTimezoneOffset is not a function` error message:

![Captura de tela de 2022-10-29 15-37-48](https://user-images.githubusercontent.com/14809968/198847998-94718e9b-0745-46b5-8b16-50752ac7b6a3.png)

Directly querying it results in rows contanining data like:

s | p | o1 | o2
-- | -- | -- | --
http://each.usp.br/Observation/1639690208#press | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | "92683.500000 hPa"^^<http://w3id.org/lindt/custom_datatypes#pressure> | 2021-12-16T21:30:08.077998Z

Is the DateTime format in the data source, wrong?

Thanks in advance.

**Comment by namedgraph** [comment] 2022-11-01 14:09
Hi again. No the data looks correct. I think the problem is that the conversion from the SPARQL results JSON to `DataTable` treats date(time)s as string.

**Comment by namedgraph** [comment] 2022-11-01 15:25
@FNakano it's now fixed in f83fd5c560b1be72b7b321dd936a2932e358fadc. Merged to `develop`.

**Closed by namedgraph** 2022-11-01 15:25 UTC

**Comment by FNakano** [comment] 2022-11-01 16:25
@namedgraph, thank you!

**Comment by FNakano** [comment] 2022-11-02 20:06
... just to show a working result...

![Captura de tela de 2022-11-02 17-03-14](https://user-images.githubusercontent.com/14809968/199592154-95905e37-3727-45a2-aba0-94eebecabeea.png)

**Comment by namedgraph** [comment] 2022-11-02 20:07
Beautiful :) Glad it helped.

**Comment by namedgraph** [comment] 2022-11-02 20:33
@FNakano what features are you using mostly?

**Comment by FNakano** [comment] 2022-11-03 16:03
@namedgraph , I intend to use LinkedDataHub to design/deploy sensor data analysis and decision-making based on (web) semantics.

**Comment by namedgraph** [comment] 2022-11-03 16:23
Thanks :) What I meant is what features in LDH are you using/planning to use: storing queries, creating/editing documents, creating structured content etc. That would be helpful to know.

**Comment by FNakano** [comment] 2022-11-03 16:56
Oh! I missed the abstraction level... sorry...
- store queries - yes;
- create documents and other content- yes;
- (re-) organize content based on preferences - yes;
- store knowledge graphs, merge with sensor data, query the resulting graph - yes
